#!/bin/bash
# GoDaddy DNS Configuration Helper

echo "======================================================"
echo "GoDaddy DNS Configuration for Render"
echo "======================================================"
echo ""
echo "You'll need to add these DNS records in GoDaddy:"
echo ""
echo "1. For www.yourdomain.com:"
echo "   Type: CNAME"
echo "   Name: www"
echo "   Value: your-app-name.onrender.com"
echo "   TTL: 600"
echo ""
echo "2. For yourdomain.com (root domain):"
echo "   Type: CNAME"
echo "   Name: @"
echo "   Value: your-app-name.onrender.com"
echo "   TTL: 600"
echo ""
echo "   OR (if CNAME for @ doesn't work):"
echo "   Type: A"
echo "   Name: @"
echo "   Value: [IP address from Render]"
echo "   TTL: 600"
echo ""
echo "======================================================"
echo "Steps to configure in GoDaddy:"
echo "======================================================"
echo "1. Log in to GoDaddy.com"
echo "2. Go to 'My Products'"
echo "3. Find your domain and click 'DNS'"
echo "4. Click 'Add' to add new records"
echo "5. Enter the details above"
echo "6. Click 'Save'"
echo ""
echo "Note: DNS changes can take 24-48 hours but usually"
echo "      work within 30 minutes to 2 hours"
echo ""
echo "Verify DNS propagation at: https://dnschecker.org"
echo "======================================================"
